// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryhztxxktvtavaecedlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aHp0eHhrdHZ0YXZhZWNlZGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzQzMzUsImV4cCI6MjA3MTk1MDMzNX0._rBC6sn9BUxHDfMBovphZwUL4CIMzOBQJZ1BbWRCmo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});